services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: dms_meta
      POSTGRES_USER: dms
      POSTGRES_PASSWORD: dms
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schemas:/schema:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dms -d dms_meta"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:0.5.13
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 5 &&
        if ! ollama list | grep -q 'llama3.1:8b'; then
          echo 'Model llama3.1:8b not found, pulling...'
          ollama pull llama3.1:8b
        else
          echo 'Model llama3.1:8b already exists, skipping download'
        fi &&
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "ollama list | grep -q 'llama3.1:8b' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite-blob-storages
    command: ["azurite", "--location", "/data", "--blobHost", "0.0.0.0", "--skipApiVersionCheck"]
    ports:
      - "10000:10000"
    volumes:
      - azdata:/data
    healthcheck:
      test: ["CMD", "pgrep", "-f", "azurite"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-worker:
    image: python:3.11-slim
    container_name: celery-worker
    command: >
      sh -c "
        apt-get update && \
        apt-get install -y --no-install-recommends poppler-utils && \
        rm -rf /var/lib/apt/lists/* && \
        python -m venv /opt/venv && \
        /opt/venv/bin/pip install --upgrade pip && \
        /opt/venv/bin/pip install . && \
        /opt/venv/bin/pip uninstall -y opencv-python opencv-contrib-python || true && \
        /opt/venv/bin/python -m celery -A src.celery_app worker --loglevel=info --concurrency=2
      "
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
      - postgres
      - azurite
    environment:
      - PYTHONPATH=/app
      - IN_DOCKER=1
    healthcheck:
      test: ["CMD", "/opt/venv/bin/python", "-m", "celery", "-A", "src.celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3e 

volumes:
  pgdata:
  azdata:
  ollama_data: 