services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: dms_meta
      POSTGRES_USER: dms
      POSTGRES_PASSWORD: dms
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/schema/schema.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dms -d dms_meta"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:0.5.13
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "pgrep", "-f", "ollama"]
      interval: 30s
      timeout: 10s
      retries: 5

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite-blob-storages
    command: ["azurite", "--location", "/data", "--blobHost", "0.0.0.0"]
    ports:
      - "10000:10000"
    volumes:
      - azdata:/data
    healthcheck:
      test: ["CMD", "pgrep", "-f", "azurite"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  azdata:
  ollama_data: 